[platformio]
default_envs = collar_xiao_sx1262, receiver_heltec_v2
src_dir = firmware

[env]
framework = arduino
monitor_speed = 115200
build_flags = -Ifirmware/common
lib_deps =
  jgromes/RadioLib @ ^7.7.1

[env:collar_xiao_sx1262]
platform = espressif32
board = seeed_xiao_esp32s3
build_src_filter =
  +<collar/>
  -<receiver/>
lib_deps =
  ${env.lib_deps}
  mikalhart/TinyGPSPlus @ ^1.0.3

[env:receiver_heltec_v2]
platform = espressif32
board = heltec_wifi_lora_32_V2
build_src_filter =
  -<collar/>
  +<receiver/>
lib_deps = ${env.lib_deps}
